// /secure/login.c - Login handler for Dawn of the Dragons
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>
#include "/include/master.h"

nosave string name;

void create() {
    write("Welcome to Dawn of the Dragons!\n");
    write("Enter your name: ");
    input_to("get_name");
}

void get_name(string str) {
    object player; // Declare at top
    if (!str || str == "") {
        write("Name cannot be empty. Try again: ");
        input_to("get_name");
        return;
    }
    name = lower_case(str);
    write("Hello, " + capitalize(name) + "!\n");
    player = clone_object("/global/player");
    if (!player) {
        write("Error: Could not create player object.\n");
        destruct(this_object());
        return;
    }
    player->set_player_name(name);
    if (!player->move(START_ROOM)) {
        write("Error: Could not move to starting room.\n");
        destruct(player);
        destruct(this_object());
        return;
    }
    exec(player, this_object());
    destruct(this_object());
}
