#!/bin/bash

# fix_discworld_lib.sh - Automate compatibility fixes for Discworld lib with FluffOS
# Generated by Grok 3, March 4, 2025

LIB_DIR="/mnt/home2/grok/lib"
FLUFFOS_INCLUDE="/mnt/home2/grok/fluffos/include"

# Files to check
FILES=(
    "$LIB_DIR/secure/simul_efun.c"
    "$LIB_DIR/room.c"
    "$LIB_DIR/monster.c"
    "$LIB_DIR/master.c"
)

# Fix function
fix_file() {
    local file=$1
    if [[ -f "$file" ]]; then
        echo "Processing $file"
        sed -i 's/crypt(/sha512_crypt(/g' "$file"  # Update crypt to sha512_crypt
        sed -i 's/#include "mudos.h"/#include "config.h"/g' "$file"  # Update include
        sed -i 's/int/long long/g' "$file"  # Add 64-bit support
        sed -i "s|\"/include/|\"$FLUFFOS_INCLUDE/|g" "$file"  # Adjust include paths
        echo "Fixed $file"
    else
        echo "File $file not found"
    fi
}

# Execute fixes
for file in "${FILES[@]}"; do
    fix_file "$file"
done

# Additional directories
for dir in "$LIB_DIR"/{std,obj,rooms}; do
    if [[ -d "$dir" ]]; then
        for subfile in "$dir"/*.c; do
            fix_file "$subfile"
        done
    fi
done

echo "Fixes applied. Recompile with FluffOS: cd /path/to/fluffos && cmake .. -DMARCH_NATIVE=OFF && make"
