// /global/player.c - Player object for Dawn of the Dragons
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>
#include <player.h>

inherit "/std/object";

nosave string player_name;
nosave int last_login;

void create() {
    ::create();
    set_name("guest");
    player_name = "guest";
    last_login = time();
    add_action("do_move", "go");
}

void setup() {
    set_short("A new adventurer");
    set_long("A fresh soul in Dawn of the Dragons.\n");
}

int do_move(string dir) {
    object env = environment(this_object());
    string dest = env->query_exit(dir);
    if (!dest) {
        write("You can’t go that way!\n");
        return 1;
    }
    move_object(dest);
    write("You move " + dir + ".\n");
    say(player_name + " moves " + dir + ".\n");
    return 1;
}

void set_player_name(string name) {
    player_name = name;
    set_name(name);
    set_short(capitalize(name));
}

string query_player_name() { return player_name; }
int query_last_login() { return last_login; }
