// /room/market.c - Second room for movement test
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>

inherit "/std/room";

void create() {
    ::create();
    set_short("Market Street");
    set_long("A busy street filled with stalls. West returns to the square.\n");
    add_exit("west", "/room/start");
}
