// /room/start.c - Temporary newbie start room
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>

inherit "/std/room";

void create() {
    ::create();
    set_short("Ankh-Morpork Square");
    set_long("A bustling square in Ankh-Morpork. Paths lead south and east.\n");
    add_exit("south", "/room/void");
    add_exit("east", "/room/market");
}
