// /room/void.c - Starting room for Dawn of the Dragons
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>

inherit "/std/room";

void create() {
    ::create();
    set_short("The Void");
    set_long("A dark, endless expanse. A path leads north.\n");
    add_exit("north", "/room/start");
}
