// /std/room.c - Base room for Dawn of the Dragons
// Optimized for FluffOS, March 4, 2025
// Generated by Grok 3

#include <config.h>

inherit "/std/object";

mapping exits;

void create() {
    ::create();
    exits = ([ ]);
    set_short("A generic room");
    set_long("An unremarkable space.\n");
}

void add_exit(string dir, string dest) {
    exits[dir] = dest;
}

string query_exit(string dir) {
    return exits[dir];
}
